### ISSUE TITLE
Update major version suffix for Go installation

### ISSUE THREAD

**Issue by chasefleming** [onflowser/flowser#199]
It would be nice to update Flowser in Flow CLI to v3 but the go.mod file needs to be update from v2: https://github.com/onflowser/flowser/blob/81bf85869c9a56b4696176d47e9bc7691929f829/go.mod#L1

Can you please update?

**Comment by bartolomej** [comment]
@chasefleming I believe there is probably no need for that since the Flowser installation logic always downloads the latest release, so users should be able to download the latest v3 release with the current go package version.

Can confirm that flowser v3 is downloaded when running `flow flowser` (without having it installed already).

**Comment by chasefleming** [comment]
Ok great thanks. Closing.
