### ISSUE TITLE
Improve Types on frontend

### ISSUE THREAD

**Issue by jgololicic** [onflowser/flowser#42]
in frontend most of the time type "any" is used. Defined custom types

**Comment by bartolomej** [comment]
I've labeled this issue as "good first issue", because it doesn't require much familiarity with flowser codebase to get started.

Required knowledge:
- basic TypeScript (type definitions, union types? - combining types, etc.)
- React.js (components, hooks, react-query,..) and usage with TypeScript (for defining prop types, etc.)
- familiarity with REST APIs (how is data send to / returned from the server, etc)

To see available endpoints, head over to https://app.flowser.dev/api (or http://localhost:3001 in development), where you can find a complete list of endpoints. 
You can just play around with the endpoints to see data structures that are used in REST API and implement those in TypeScript (frontend codebase).

**Comment by bartolomej** [comment]
Fixed in https://github.com/onflowser/flowser/pull/89.
